[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Persistent volumes for data storage
[[volumes]]
mountPath = "/app/development/src/execution-sandbox"

[[volumes]]
mountPath = "/app/development/src/static/appdocs"
